/**
 * Workbook copy tables: human labels for the summary, KPI names,
 * coverage notes and assumption lines, in English and Arabic.
 *
 * Source: the planning locale reference behind the in-repo
 * translation-key manifest; canonical home is the owned locale
 * catalog (Cloud/i18n lane). Ledger headers, issue enums and
 * methodology items localize through the same tables.
 */
import type { Locale } from '@rowfolio/contracts';

const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    "metric.revenue": "Revenue",
    "metric.target_revenue": "Revenue target",
    "metric.operating_cost": "Operating cost",
    "metric.order_volume": "Order volume",
    "metric.downtime_minutes": "Downtime",
    "metric.maintenance_cost": "Maintenance cost",
    "metric.csat_score": "Satisfaction score",
    "metric.contribution": "Operating contribution",
    "metric.margin": "Contribution margin",
    "metric.marginDelta": "Margin change, percentage points",
    "metric.targetGap": "Difference from target",
    "metric.ordersChange": "Order volume change",
    "metric.downtimeChange": "Downtime change",
    "quality.duplicate": "Duplicate rows",
    "quality.category": "Inconsistent category cells",
    "quality.missing": "Missing optional values",
    "coverage.scheduledComplete": "Every scheduled period is complete",
    "coverage.allSource": "All selected source records",
    "coverage.partial": "Incomplete period: comparison unavailable",
    "export.title": "A report you can take with you",
    "export.includesScenario": "Includes the {change} operating-cost scenario",
    "common.baseline": "Baseline",
    "common.source": "Source",
    "common.allRegions": "All regions",
    "common.rows": "Source rows",
    "common.metric": "Metric",
    "common.technicalDetails": "Technical details",
    "unit.records": "records",
    "unit.pp": "percentage points",
    "workspace.scope": "Analysis scope",
    "workspace.records": "{raw} input records · {clean} retained",
    "evidence.title": "Calculation and source rows",
    "evidence.hash": "Source file fingerprint",
    "scenario.title": "Change operating costs",
    "scenario.assumption.revenueFixed": "Revenue stays fixed",
    "scenario.costChange": "Operating cost change",
    "scenario.assumption.mechanical": "Only selected operating costs change; this is not a forecast",
    "table.metric": "Metric",
    "table.value": "Value",
    "table.unit": "Unit",
    "table.coverage": "Coverage",
    "table.issue": "Issue",
    "table.kind": "Kind",
    "table.row": "Row",
    "table.field": "Field",
    "table.original": "Original",
    "table.normalized": "Normalized",
    "table.status": "Status",
    "table.action": "Action",
    "table.approval": "Approval",
    "quality.kind.duplicate": "Duplicate row",
    "quality.kind.missing": "Missing value",
    "quality.kind.category": "Inconsistent category",
    "quality.kind.malformed": "Unreadable cell",
    "quality.kind.formula-cache": "Stale formula result",
    "quality.kind.header": "Header problem",
    "quality.kind.ambiguous-date": "Ambiguous date",
    "quality.kind.precision": "Precision limit",
    "quality.kind.unsupported": "Unsupported value",
    "quality.status.proposed": "Suggested",
    "quality.status.resolved": "Resolved",
    "quality.status.unresolved": "Unresolved",
    "quality.status.ignored": "Left as found",
    "quality.action.none": "None",
    "quality.action.exclude-row": "Row excluded",
    "quality.action.map-category": "Category unified",
    "quality.action.confirm-type": "Type confirmed",
    "quality.action.use-cache": "Cached result used",
    "quality.approval.none": "Automatic check",
    "quality.approval.user": "You confirmed",
    "quality.approval.sample-manifest": "Bundled sample rule",
    "sheet.diagnostics": "Diagnostics",
    "method.policy": "Policy",
    "method.analysis": "Analysis",
    "method.revision": "Table revision",
    "method.template": "Template",
    "method.precision": "Precision",
    "method.precision.halfUp": "Half-up rounding, 40-digit precision",
    "method.limits": "Limits",
    "method.proof": "Proof {id}",
    "method.scope": "Scope",
    "method.noForecast": "No forecast or causal claim. Cached results are authoritative; recalculation on open is an aid.",
    "column.type.decimal": "Decimal",
    "column.type.date": "Date",
    "column.type.mixed": "Mixed",
    "column.type.text": "Text",
    "column.type.integer": "Whole number",
    "coverage.eligible": "eligible {eligible}/{total}",
  },
  ar: {
    "metric.revenue": "الإيرادات",
    "metric.target_revenue": "الإيرادات المستهدفة",
    "metric.operating_cost": "تكاليف التشغيل",
    "metric.order_volume": "حجم الطلبات",
    "metric.downtime_minutes": "وقت التوقف",
    "metric.maintenance_cost": "تكلفة الصيانة",
    "metric.csat_score": "درجة الرضا",
    "metric.contribution": "المساهمة التشغيلية",
    "metric.margin": "هامش المساهمة التشغيلية",
    "metric.marginDelta": "تغيّر الهامش بالنقاط المئوية",
    "metric.targetGap": "الفرق عن المستهدف",
    "metric.ordersChange": "التغيّر في حجم الطلبات",
    "metric.downtimeChange": "التغيّر في وقت التوقف",
    "quality.duplicate": "صفوف مكررة",
    "quality.category": "خلايا فئات غير متسقة",
    "quality.missing": "قيم اختيارية مفقودة",
    "coverage.scheduledComplete": "اكتملت كل الفترات المجدولة",
    "coverage.allSource": "جميع سجلات المصدر المحددة",
    "coverage.partial": "فترة غير مكتملة: المقارنة غير متاحة",
    "export.title": "تقرير يمكنك الاحتفاظ به",
    "export.includesScenario": "يتضمن سيناريو تغيّر تكاليف التشغيل بنسبة {change}",
    "common.baseline": "الحالة الأساسية",
    "common.source": "المصدر",
    "common.allRegions": "جميع المناطق",
    "common.rows": "صفوف المصدر",
    "common.metric": "مقياس",
    "common.technicalDetails": "تفاصيل تقنية",
    "unit.records": "سجلات",
    "unit.pp": "نقاط مئوية",
    "workspace.scope": "نطاق التحليل",
    "workspace.records": "سجلات المصدر: {raw} · السجلات المحتفظ بها: {clean}",
    "evidence.title": "الحساب وصفوف المصدر",
    "evidence.hash": "بصمة ملف المصدر",
    "scenario.title": "غيّر تكاليف التشغيل",
    "scenario.assumption.revenueFixed": "تبقى الإيرادات ثابتة",
    "scenario.costChange": "التغيّر في تكاليف التشغيل",
    "scenario.assumption.mechanical": "تتغيّر تكاليف التشغيل المحددة فقط؛ وهذا ليس توقعاً",
    "table.metric": "المؤشر",
    "table.value": "القيمة",
    "table.unit": "الوحدة",
    "table.coverage": "التغطية",
    "table.issue": "المشكلة",
    "table.kind": "النوع",
    "table.row": "الصف",
    "table.field": "الحقل",
    "table.original": "الأصلي",
    "table.normalized": "المُوحَّد",
    "table.status": "الحالة",
    "table.action": "الإجراء",
    "table.approval": "الموافقة",
    "quality.kind.duplicate": "صف مكرر",
    "quality.kind.missing": "قيمة مفقودة",
    "quality.kind.category": "فئة غير متسقة",
    "quality.kind.malformed": "خلية غير مقروءة",
    "quality.kind.formula-cache": "نتيجة صيغة قديمة",
    "quality.kind.header": "مشكلة في الترويسة",
    "quality.kind.ambiguous-date": "تاريخ غامض",
    "quality.kind.precision": "حد الدقة",
    "quality.kind.unsupported": "قيمة غير مدعومة",
    "quality.status.proposed": "مقترحة",
    "quality.status.resolved": "مُعالجة",
    "quality.status.unresolved": "غير مُعالجة",
    "quality.status.ignored": "تُركت كما هي",
    "quality.action.none": "لا شيء",
    "quality.action.exclude-row": "استُبعد الصف",
    "quality.action.map-category": "وُحّدت الفئة",
    "quality.action.confirm-type": "أُكّد النوع",
    "quality.action.use-cache": "استُخدمت النتيجة المخزنة",
    "quality.approval.none": "فحص تلقائي",
    "quality.approval.user": "أكّدتَها",
    "quality.approval.sample-manifest": "قاعدة النموذج المضمّن",
    "sheet.diagnostics": "التشخيص",
    "method.policy": "السياسة",
    "method.analysis": "التحليل",
    "method.revision": "مراجعة الجدول",
    "method.template": "القالب",
    "method.precision": "الدقة",
    "method.precision.halfUp": "تقريب نصف-أعلى، بدقة ٤٠ خانة",
    "method.limits": "الحدود",
    "method.proof": "إثبات {id}",
    "method.scope": "النطاق",
    "method.noForecast": "لا توقع ولا ادعاء سببي. النتائج المخزنة هي المرجع؛ إعادة الحساب عند الفتح وسيلة مساعدة.",
    "column.type.decimal": "عدد عشري",
    "column.type.date": "تاريخ",
    "column.type.mixed": "مختلط",
    "column.type.text": "نص",
    "column.type.integer": "عدد صحيح",
    "coverage.eligible": "مؤهلة {eligible}/{total}",
  },
};

/** Localized label for a declared translation key. Throws on unknown keys. */
export function sheetLabel(locale: Locale, key: string): string {
  const value = STRINGS[locale][key];
  if (value === undefined) {
    throw new Error(`missing workbook label for key ${JSON.stringify(key)} (${locale})`);
  }
  return value;
}

/** True when both locales carry the key. */
export function hasSheetLabel(key: string): boolean {
  return STRINGS.en[key] !== undefined && STRINGS.ar[key] !== undefined;
}
