#!/usr/bin/env node
/**
 * Regenerate packages/contracts/src/types.ts from the authoritative JSON Schema.
 *
 * Port of the planning package's scripts/generate_types.py: emits one structural
 * `export type` per $defs entry, in schema order. The output is intentionally
 * byte-stable for a given schema — the contract test asserts regeneration
 * produces no diff.
 *
 * Usage: node packages/contracts/scripts/generate-types.mjs [--check]
 *   --check  compare with the committed file and exit 1 on any difference
 */
import console from 'node:console';
import process from 'node:process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SCHEMA_PATH = join(ROOT, 'source', 'rowfolio.schema.json');
const OUT_PATH = join(ROOT, 'src', 'types.ts');

const HEADER =
  '// GENERATED by packages/contracts/scripts/generate-types.mjs. Edit packages/contracts/source/rowfolio.schema.json, not this file.\n' +
  '// Structural types do not enforce decimal patterns, ranges, IDs or cross-field invariants.\n';

const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf8'));

function ts(s) {
  if (typeof s !== 'object' || s === null) throw new Error(`Unsupported schema node: ${String(s)}`);
  if ('$ref' in s) return s.$ref.split('/').pop();
  if ('const' in s) return JSON.stringify(s.const);
  if ('enum' in s) return s.enum.map((v) => JSON.stringify(v)).join(' | ');
  if ('oneOf' in s || 'anyOf' in s) {
    const variants = s.oneOf ?? s.anyOf;
    return '(' + variants.map(ts).join(' | ') + ')';
  }
  const t = s.type;
  if (Array.isArray(t)) return '(' + t.map((a) => ts({ ...s, type: a })).join(' | ') + ')';
  if (t === 'array') return `Array<${ts(s.items)}>`;
  if (t === 'object') {
    const props = s.properties;
    if ((props === undefined || Object.keys(props).length === 0) && typeof s.additionalProperties === 'object') {
      return `Record<string, ${ts(s.additionalProperties)}>`;
    }
    const required = new Set(s.required ?? []);
    const body = Object.entries(props ?? {})
      .map(([k, v]) => `${JSON.stringify(k)}${required.has(k) ? '' : '?'}: ${ts(v)};`)
      .join(' ');
    return `{ ${body} }`;
  }
  if (t === 'integer' || t === 'number') return 'number';
  if (t === 'string' || t === 'boolean' || t === 'null') return t;
  throw new Error(`Unsupported schema: ${JSON.stringify(s)}`);
}

const text =
  HEADER +
  Object.entries(schema.$defs)
    .map(([name, def]) => `export type ${name} = ${ts(def)};\n`)
    .join('\n');

if (process.argv.includes('--check')) {
  const current = readFileSync(OUT_PATH, 'utf8');
  if (current !== text) {
    console.error(`types.ts is stale: regenerate with \`pnpm --filter @rowfolio/contracts generate:types\``);
    process.exit(1);
  }
  console.log('types.ts matches the schema.');
} else {
  writeFileSync(OUT_PATH, text);
  console.log(`Wrote ${OUT_PATH}`);
}
