/* global Buffer, TextEncoder, process, console */
/**
 * generate.mjs — produce the ingest fixture corpus deterministically.
 *
 *   node fixtures/ingest/generate.mjs          → write fixtures + manifest
 *   node fixtures/ingest/generate.mjs --check  → verify manifest hashes match
 *
 * All content is synthetic. Malformed/hostile files exist so the adapter's
 * typed-failure behavior is exercised against bytes real tools never emit.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildZip, sha256Hex, zipBytes } from './zipkit.mjs';
import { buildXlsx } from './xlsxkit.mjs';

const DIR = join(dirname(fileURLToPath(import.meta.url)), 'generated');
const enc = (s) => new TextEncoder().encode(s);

/** @type {Record<string, {bytes: Uint8Array, note: string}>} */
const fixtures = {};

// ---------- valid XLSX fixtures ----------

// Types + formula/cache coverage in one small workbook.
fixtures['types-and-formulas.xlsx'] = {
  note: 'mixed types: text, number, boolean, formula with and without cached value, error cell, empty cell',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Data',
        rows: [
          ['name', 'qty', 'unit_cost', 'total', 'flag'],
          ['widget', 4, { t: 'n', v: 2.5, fmt: 3 }, { t: 'f', f: 'B2*C2', v: 10 }, true],
          ['gadget', 7, { t: 'n', v: 1.25, fmt: 3 }, { t: 'f', f: 'B3*C3' }, false], // no cached value
          ['broken', null, { t: 'e', v: '#DIV/0!' }, { t: 'f', f: 'B4/C4', v: '#DIV/0!' }, null],
        ],
      },
    ],
  }),
};

fixtures['multi-sheet-hidden.xlsx'] = {
  note: '3 sheets: first visible (small), second hidden (table), third veryHidden; non-first-sheet + hidden opt-in',
  bytes: buildXlsx({
    sheets: [
      { name: 'Cover', rows: [['title'], ['nothing here']] },
      { name: 'Payload', hidden: true, rows: [['k', 'v'], ['a', 1], ['b', 2]] },
      { name: 'Secrets', veryHidden: true, rows: [['x'], [9]] },
    ],
  }),
};

fixtures['non-row1-header.xlsx'] = {
  note: 'title + note rows above the real header at row 4; data 5..8',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Report',
        rows: [
          ['Quarterly export'],
          ['generated by fixture kit'],
          [],
          ['id', 'name', 'amount'],
          ['a', 'alpha', 10],
          ['b', 'beta', 20],
          ['c', 'gamma', 30],
          ['d', 'delta', 40],
        ],
      },
    ],
  }),
};

fixtures['dates-1900.xlsx'] = {
  note: '1900 date system: valid serials plus serial 60 (the fake 1900-02-29) and serial 0',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Dates',
        rows: [
          ['label', 'serial'],
          ['epoch', { t: 'd', serial: 1 }],
          ['fake-feb29', { t: 'd', serial: 60 }],
          ['mar1', { t: 'd', serial: 61 }],
          ['zero', { t: 'd', serial: 0 }],
          ['builtin14', { t: 'd', serial: 45000, fmt: 14 }],
        ],
      },
    ],
  }),
};

fixtures['dates-1904.xlsx'] = {
  note: '1904 date system flag; serial 60 is a real date here, serial 0 is valid epoch',
  bytes: buildXlsx({
    date1904: true,
    sheets: [
      {
        name: 'Dates',
        rows: [
          ['label', 'serial'],
          ['epoch', { t: 'd', serial: 0 }],
          ['serial60', { t: 'd', serial: 60 }],
        ],
      },
    ],
  }),
};

fixtures['merged-and-hidden.xlsx'] = {
  note: 'merged A2:B2 inside table, hidden row 5, hidden column 3',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Grid',
        merges: ['A2:B2'],
        hiddenRows: [5],
        hiddenCols: [3],
        rows: [
          ['a', 'b', 'c'],
          ['merged', null, 1],
          ['x', 'y', 2],
          ['p', 'q', 3],
          ['hidden-row', 'z', 4],
        ],
      },
    ],
  }),
};

fixtures['external-refs.xlsx'] = {
  note: 'externalLink part + TargetMode=External rel — disclosed, never resolved',
  bytes: buildXlsx({
    externalLinks: true,
    sheets: [
      {
        name: 'Calc',
        rows: [
          ['x', 'y'],
          [1, { t: 'f', f: "[1]Sheet1!A1*2", v: 4 }],
        ],
      },
    ],
  }),
};

fixtures['dup-headers.xlsx'] = {
  note: 'duplicate and blank header cells',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Wide',
        rows: [
          ['id', 'id', '', 'amount', 'amount'],
          [1, 'one', 'x', 10, 11],
          [2, 'two', 'y', 20, 21],
        ],
      },
    ],
  }),
};

// ---------- hostile / rejected XLSX ----------

fixtures['ole2-xls.xlsx'] = {
  note: 'OLE2 compound magic (real .xls bytes renamed .xlsx) → UNSUPPORTED ole2-container',
  bytes: zipBytes(new Uint8Array([0xd0, 0xcf, 0x11, 0xe0, 0xa6, 0xb1, 0x1a, 0xe1]), new Uint8Array(64)),
};

fixtures['macro-xlsm.xlsx'] = {
  note: 'macroEnabled content type + vbaProject.bin → UNSUPPORTED macro-enabled',
  bytes: buildXlsx({
    macro: true,
    sheets: [{ name: 'S', rows: [['a'], [1]] }],
  }),
};

fixtures['not-a-workbook.xlsx'] = {
  note: 'valid zip, no content types / no workbook part → UNSUPPORTED not-a-workbook',
  bytes: buildZip([{ name: 'hello.txt', data: enc('just a zip') }]),
};

fixtures['ods-masquerade.xlsx'] = {
  note: 'mimetype says opendocument → UNSUPPORTED ods-masquerade',
  bytes: buildZip([
    { name: 'mimetype', data: enc('application/vnd.oasis.opendocument.spreadsheet'), method: 0 },
    { name: '[Content_Types].xml', data: enc('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/></Types>') },
  ]),
};

fixtures['encrypted-entries.xlsx'] = {
  note: 'central-directory encryption flag forged on entries → UNSUPPORTED encrypted-entry',
  bytes: buildZip(
    [
      { name: '[Content_Types].xml', data: enc('<Types/>'), flags: 0x0801 }, // bit0 = encrypted
    ],
  ),
};

fixtures['path-traversal.xlsx'] = {
  note: 'entry name ../evil.xml → INVALID path-traversal',
  bytes: buildZip([
    { name: '../evil.xml', data: enc('x') },
    { name: '[Content_Types].xml', data: enc('<Types/>') },
  ]),
};

fixtures['dup-entry.xlsx'] = {
  note: 'duplicate normalized entry names → INVALID duplicate-entry',
  bytes: buildZip([
    { name: 'xl/workbook.xml', data: enc('<a/>') },
    { name: 'xl/workbook.xml', data: enc('<b/>') },
  ]),
};

fixtures['bomb.xlsx'] = {
  note: 'deflate bomb: ~80MiB of zeros, tiny compressed → LIMIT_EXCEEDED (expanded/entry)',
  bytes: buildZip([
    { name: 'xl/worksheets/sheet1.xml', data: Buffer.alloc(80 * 1024 * 1024) },
    { name: '[Content_Types].xml', data: enc('<Types/>') },
  ]),
};

fixtures['declared-lie.xlsx'] = {
  note: 'CD declared uncompressed size lies (4 bytes) while entry inflates 80MiB → LIMIT on actual bytes',
  bytes: buildZip([
    { name: 'big.bin', data: Buffer.alloc(80 * 1024 * 1024), declaredUncompressedSize: 4 },
    { name: 'x.txt', data: enc('ok') },
  ]),
};

fixtures['too-many-entries.xlsx'] = {
  note: '2001 entries → LIMIT_EXCEEDED zip.entries',
  bytes: (() => {
    const files = [{ name: '[Content_Types].xml', data: enc('<Types/>') }];
    for (let i = 0; i < 2001; i += 1) files.push({ name: `f${i}.bin`, data: enc('x') });
    return buildZip(files);
  })(),
};

fixtures['truncated-zip.xlsx'] = {
  note: 'EOCD present but central directory truncated → INVALID',
  bytes: (() => {
    const good = buildZip([{ name: 'a.txt', data: enc('x') }]);
    return good.subarray(0, good.length - 10); // cut into the CD/EOCD tail
  })(),
};

fixtures['garbage-pk.xlsx'] = {
  note: 'PK magic then garbage, no EOCD → INVALID eocd-missing',
  bytes: zipBytes('PK\x03\x04', Buffer.alloc(32, 0xff)),
};

fixtures['malformed-xml.xlsx'] = {
  note: 'workbook.xml is not XML → INVALID (SheetJS parse fails)',
  bytes: buildZip([
    { name: '[Content_Types].xml', data: enc('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>') },
    { name: '_rels/.rels', data: enc('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>') },
    { name: 'xl/workbook.xml', data: enc('this is not <xml at all') },
    { name: 'xl/_rels/workbook.xml.rels', data: enc('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>') },
    { name: 'xl/worksheets/sheet1.xml', data: enc('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>x</t></is></c></row></sheetData></worksheet>') },
  ]),
};

// ---------- CSV fixtures ----------

fixtures['quoted-newlines.csv'] = {
  note: 'quoted cells containing newlines and delimiters; sparse physical rows',
  bytes: enc('id,note,amount\n1,"line one\nline two",10\n2,"comma, inside",20\n3,"semi;inside",30\n4,"quote ""inner""",40\n'),
};

fixtures['semicolon.csv'] = {
  note: 'consistent semicolon delimiter',
  bytes: enc('a;b;c\n1;2;3\n4;5;6\n'),
};

fixtures['ambiguous.csv'] = {
  note: 'rows consistent under BOTH comma and semicolon → AMBIGUOUS_INPUT',
  bytes: enc('a,b;c\n1,2;3\n4,5;6\n'),
};

fixtures['invalid-utf8.csv'] = {
  note: 'raw 0xFF byte → INVALID csv.invalid-utf8',
  bytes: Buffer.concat([enc('a,b\n'), Buffer.from([0xff, 0xfe, 0x61]), enc('\n')]),
};

fixtures['leading-zeros.csv'] = {
  note: 'identifiers that must stay text ("007", "01", "+1", "1e3")',
  bytes: enc('code,label\n007,bond\n01,priority\n+1,phone\n1e3,sci\n3.140,pi\n'),
};

fixtures['ragged.csv'] = {
  note: 'rows with fewer/more fields than the header + blank lines skipped',
  bytes: enc('a,b,c\n1,2,3\n4,5\n6,7,8,9\n\n\n10,11,12\n'),
};

fixtures['title-rows.csv'] = {
  note: 'comment lines above the real header at physical line 3',
  bytes: enc('# report export\n# generated 2026-01-01\nid,name\n1,a\n2,b\n'),
};

fixtures['empty.csv'] = { note: 'zero bytes → INVALID csv.empty / empty-input', bytes: new Uint8Array(0) };

fixtures['whitespace.csv'] = { note: 'only whitespace → INVALID csv.empty', bytes: enc('   \n \n') };

fixtures['bom.csv'] = { note: 'UTF-8 BOM stripped before parsing', bytes: Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), enc('a,b\n1,2\n')]) };

// ---------- wide/large (generated at test time, kept small on disk) ----------

fixtures['wide-101.xlsx'] = {
  note: '101 columns → LIMIT_EXCEEDED columns',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Wide',
        rows: [
          Array.from({ length: 101 }, (_, i) => `h${i + 1}`),
          Array.from({ length: 101 }, (_, i) => i),
        ],
      },
    ],
  }),
};

fixtures['many-rows.xlsx'] = {
  note: '50001 data rows → LIMIT_EXCEEDED rows-including-header (generated, compresses well)',
  bytes: buildXlsx({
    sheets: [
      {
        name: 'Big',
        rows: [['id', 'v'], ...Array.from({ length: 50001 }, (_, i) => [`r${i + 1}`, i])],
      },
    ],
  }),
};

// ---------- emit ----------

const check = process.argv.includes('--check');
mkdirSync(DIR, { recursive: true });

const manifest = {};
let ok = true;
for (const [name, { bytes, note }] of Object.entries(fixtures)) {
  const path = join(DIR, name);
  const hash = sha256Hex(Buffer.from(bytes));
  manifest[name] = { sha256: hash, bytes: bytes.length, note };
  if (check) {
    const existing = readFileSync(path);
    if (sha256Hex(existing) !== hash) {
      console.error(`MISMATCH ${name}`);
      ok = false;
    }
  } else {
    writeFileSync(path, bytes);
  }
}

const manifestPath = join(DIR, 'manifest.json');
if (check) {
  const existing = JSON.parse(readFileSync(manifestPath, 'utf8'));
  if (JSON.stringify(existing.files) !== JSON.stringify(manifest)) {
    console.error('MISMATCH manifest.json');
    ok = false;
  }
  if (!ok) process.exit(1);
  console.log(`verified ${Object.keys(manifest).length} fixtures`);
} else {
  writeFileSync(manifestPath, JSON.stringify({ generatedBy: 'fixtures/ingest/generate.mjs', files: manifest }, null, 2) + '\n');
  console.log(`wrote ${Object.keys(manifest).length} fixtures → ${DIR}`);
}
