// GENERATED by packages/contracts/scripts/generate-types.mjs. Edit packages/contracts/source/rowfolio.schema.json, not this file.
// Structural types do not enforce decimal patterns, ranges, IDs or cross-field invariants.
export type Decimal = string;

export type Hash = string;

export type Locale = "en" | "ar";

export type Unit = { "kind": "currency" | "count" | "minutes" | "ratio" | "percentage-point" | "score" | "unknown"; "label": string; "currency": (string | null); };

export type Scope = { "tableId": string; "periodStart": (string | null); "periodEnd": (string | null); "regions": Array<string>; "complete": boolean; "coverageNoteKey": string; };

export type SourceRef = { "id": string; "sourceHash": Hash; "workbookName": string; "format": "xlsx" | "csv"; "sheetId": string; "sheetName": string; "headerRow": number; "range": { "firstRow": number; "lastRow": number; "firstColumn": number; "lastColumn": number; }; };

export type RowSpan = { "start": number; "end": number; };

export type RowSelection = { "id": string; "sourceRefId": string; "spans": Array<RowSpan>; "rowCount": number; "fieldIds": Array<string>; "excludedRowIds": Array<string>; "maskPolicy": "all-retained" | "shared-valid" | "field-valid"; };

export type Expression = ({ "op": "literal"; "value": Decimal; } | { "op": "metric"; "metricId": string; } | { "op": "sum"; "selectionId": string; "fieldId": string; } | { "op": "add" | "subtract" | "multiply" | "divide"; "left": Expression; "right": Expression; } | { "op": "count-rows"; "selectionId": string; } | { "op": "count-issues"; "issueIds": Array<string>; });

export type Provenance = { "id": string; "sourceRefs": Array<SourceRef>; "selections": Array<RowSelection>; "expression": Expression; "result": (Decimal | null); "status": "defined" | "undefined"; "reasonKey": (string | null); "policyVersion": string; "normalizationRevision": Hash; "transformIds": Array<string>; "precision": 40; "rounding": "ROUND_HALF_UP"; };

export type Metric = { "id": string; "labelKey": string; "value": (Decimal | null); "status": "defined" | "undefined"; "reasonKey": (string | null); "unit": Unit; "scope": Scope; "eligibleRows": number; "totalRows": number; "provenanceId": string; "warnings": Array<string>; };

export type Finding = { "id": string; "ruleId": string; "kind": "target-gap" | "period-change" | "divergence" | "quality" | "trend" | "outlier" | "descriptive"; "severity": "attention" | "neutral" | "positive"; "titleKey": string; "bodyKey": string; "metricIds": Array<string>; "provenanceIds": Array<string>; "qualityIssueIds": Array<string>; "scope": Scope; "rank": { "classPriority": number; "coverage": Decimal; "magnitude": Decimal; }; "chartId": (string | null); "limitations": Array<string>; };

export type QualityIssue = { "id": string; "kind": "duplicate" | "category" | "missing" | "malformed" | "formula-cache" | "header" | "ambiguous-date" | "precision" | "unsupported"; "sourceRefId": string; "sourceRow": number; "fieldId": (string | null); "original": (string | null); "normalized": (string | null); "status": "proposed" | "resolved" | "unresolved" | "ignored"; "action": "none" | "exclude-row" | "map-category" | "confirm-type" | "use-cache"; "approval": "none" | "user" | "sample-manifest"; "canonicalSourceRow": (number | null); "messageKey": string; };

export type Column = { "id": string; "sourceColumn": number; "label": string; "type": "text" | "identifier" | "decimal" | "integer" | "date" | "boolean" | "mixed"; "role": "dimension" | "measure" | "date" | "identifier" | "unknown"; "unit": Unit; "additive": boolean; "confirmed": boolean; "nullable": boolean; };

export type CellValue = (string | boolean | null);

export type NormalizedRow = { "id": string; "sourceRow": number; "sourceRefId": string; "values": Record<string, CellValue>; };

export type NormalizedTable = { "schemaVersion": "1.0.0"; "id": string; "sourceRef": SourceRef; "normalizationRevision": Hash; "columns": Array<Column>; "rows": Array<NormalizedRow>; "qualityIssues": Array<QualityIssue>; "grain": Array<string>; "calendarDates": Array<string>; "policyVersion": string; };

export type ChartPoint = { "key": string; "labelKey": string; "values": Record<string, (Decimal | null)>; "metricIds": Array<string>; };

export type ChartSpec = { "id": string; "kind": "line" | "bars" | "target-bars" | "scenario-bars" | "quality-bars" | "distribution"; "titleKey": string; "summaryKey": string; "unit": Unit; "series": Array<{ "id": string; "labelKey": string; "semantic": "observed" | "target" | "scenario" | "attention"; }>; "points": Array<ChartPoint>; "domain": { "min": Decimal; "max": Decimal; }; "chronology": "ltr" | "not-temporal"; "scope": Scope; "provenanceIds": Array<string>; };

export type ScenarioDefinition = { "id": "operating-cost-v1"; "version": "1.0.0"; "parameter": { "id": "costChange"; "unit": "fraction"; "min": "-0.20"; "max": "0.30"; "sliderStep": "0.01"; "typedStep": "0.001"; "default": "0"; }; "requiresMetricIds": Array<string>; "aggregationPolicy": "factor-after-aggregate"; "assumptionKeys": Array<string>; };

export type ScenarioResult = { "id": string; "definitionId": "operating-cost-v1"; "baselineAnalysisId": string; "costChange": Decimal; "scope": Scope; "metrics": Array<Metric>; "provenance": Array<Provenance>; "status": "defined" | "unavailable"; "reasonKey": (string | null); };

export type QualitySummary = { "rawRows": number; "retainedRows": number; "issueCount": number; "resolved": number; "unresolved": number; };

export type AnalysisSnapshot = { "schemaVersion": "1.0.0"; "id": string; "tableId": string; "sourceHash": Hash; "normalizationRevision": Hash; "analysisVersion": "1.0.0"; "scope": Scope; "metrics": Array<Metric>; "findings": Array<Finding>; "provenance": Array<Provenance>; "charts": Array<ChartSpec>; "qualitySummary": QualitySummary; };

export type SlideModel = { "id": string; "kind": "summary" | "kpis" | "finding" | "scenario" | "quality" | "methodology" | "descriptive"; "title": string; "subtitle": string; "metricIds": Array<string>; "findingIds": Array<string>; "chartIds": Array<string>; "notes": Array<string>; };

export type SheetModel = { "id": "summary" | "clean" | "quality" | "kpis" | "methodology"; "name": string; "direction": "ltr" | "rtl"; };

export type ExportModel = { "schemaVersion": "1.0.0"; "exportId": string; "analysisId": string; "sourceHash": Hash; "locale": Locale; "numberingSystem": "latn" | "arab"; "createdAt": string; "templateVersion": "1.0.0"; "scope": Scope; "table": NormalizedTable; "metrics": Array<Metric>; "findings": Array<Finding>; "charts": Array<ChartSpec>; "provenance": Array<Provenance>; "qualitySummary": QualitySummary; "scenario": (ScenarioResult | null); "slides": Array<SlideModel>; "sheets": Array<SheetModel>; };

export type ExportArtifact = { "exportId": string; "format": "xlsx" | "pptx"; "mime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | "application/vnd.openxmlformats-officedocument.presentationml.presentation"; "filename": string; "byteLength": number; "sha256": Hash; "binarySlot": string; };

export type WorkerRequest = ({ "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "ingest"; "payload": { "sourceName": string; "format": "xlsx" | "csv"; "byteLength": number; "binarySlot": string; }; } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "normalize"; "payload": { "rawTableId": string; "approvedIssueIds": Array<string>; "columnConfirmations": Array<Column>; }; } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "analyze"; "payload": { "table": NormalizedTable; "scope": Scope; }; } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "scenario"; "payload": { "snapshot": AnalysisSnapshot; "definition": ScenarioDefinition; "costChange": Decimal; }; } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "export"; "payload": { "model": ExportModel; "format": "xlsx" | "pptx"; }; } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "operation": "dispose"; "payload": Record<string, never>; });

export type RawCell = { "row": number; "column": number; "raw": (string | boolean | null); "type": "text" | "number" | "boolean" | "date" | "blank" | "formula" | "error"; "formula": (string | null); "cachedValue": (string | null); };

export type RawTable = { "id": string; "sourceRef": SourceRef; "cells": Array<RawCell>; "dateSystem": "1900" | "1904" | "not-applicable"; "warnings": Array<string>; };

export type WorkerResponse = ({ "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "kind": "progress"; "stage": "preflight" | "parse" | "normalize" | "analyze" | "model" | "layout" | "charts" | "package"; "fraction": (number | null); } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "kind": "success"; "result": (RawTable | NormalizedTable | AnalysisSnapshot | ScenarioResult | ExportArtifact | { "disposed": true; }); } | { "protocolVersion": 1; "requestId": string; "sessionId": string; "revision": number; "kind": "error"; "code": "INVALID_FILE" | "LIMIT_EXCEEDED" | "AMBIGUOUS_INPUT" | "UNSUPPORTED" | "CANCELLED" | "TIMEOUT" | "EXPORT_FAILED" | "SCHEMA_MISMATCH" | "INTERNAL"; "messageKey": string; "recoverable": boolean; });

export type SampleManifest = { "schemaVersion": "1.0.0"; "datasetId": string; "seed": number; "fictional": true; "sourceSheet": string; "sourceSheetId": string; "headerRow": number; "rawRecords": number; "cleanRecords": number; "currency": "USD"; "moneyScale": 2; "periods": Array<string>; "regions": Array<string>; "sitesPerRegion": number; "grain": Array<string>; "primaryKey": Array<string>; "sourceCsvSha256": Hash; "cleanCsvSha256": Hash; "quality": { "duplicateRows": number; "categoryCells": number; "missingOptionalCells": number; "issueCount": number; "resolved": number; "unresolved": number; }; "maintenanceIsSubsetOfOperatingCost": true; "periodCoverage": string; "missingPolicy": string; "categoryPolicy": string; "notes": Array<string>; };
