#!/usr/bin/env node
/**
 * Generates tests/unit/i18n/generated/content-fixture.gen.ts from the real
 * English/Arabic locale catalogs.
 *
 * The fixture pins catalog content that string-level tests care about:
 *   - per-catalog SHA-256 (drift guard)
 *   - unit wording keys (percentage points, margins)
 *   - state copy keys (not available / not confirmed / not defined)
 *   - the longest labels per locale and their lengths
 *   - the mixed Arabic/Latin script inventory in Arabic values
 *   - placeholder usage counts per locale
 *
 * Run against a checkout that has catalogs (they live on integration until
 * merged); pass --dir to point at an explicit catalog directory:
 *
 *   node tooling/test/corpus/i18n/generate-content-fixture.ts \
 *     --dir /path/to/packages/i18n/src/locales
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveCatalogDir } from './check-catalog.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const outPath = resolve(repoRoot, 'tests/unit/i18n/generated/content-fixture.gen.ts');

const UNITS_KEYS = ['scenario.result', 'metric.marginDelta'];
const STATE_KEYS = ['common.notAvailable', 'common.unknown', 'common.undefined'];
const ARABIC_RE = /[\u0600-\u06FF]/;
const LATIN_RE = /[A-Za-z]/;
const PLACEHOLDER_RE = /\{([A-Za-z][A-Za-z0-9_]*)\}/g;

function args(argv: string[]): string | null {
  let dir: string | null = null;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--dir') dir = resolve(argv[++i] ?? '');
  }
  return dir;
}

function sha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function longestValues(catalog: Record<string, string>, count: number): { key: string; length: number }[] {
  return Object.entries(catalog)
    .map(([key, value]) => ({ key, length: [...value].length }))
    .sort((a, b) => b.length - a.length)
    .slice(0, count);
}

function mixedScriptValues(catalog: Record<string, string>): string[] {
  return Object.entries(catalog)
    .filter(([, value]) => ARABIC_RE.test(value) && LATIN_RE.test(value))
    .map(([key]) => key)
    .sort();
}

function placeholderCounts(catalog: Record<string, string>): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const value of Object.values(catalog)) {
    for (const match of String(value).matchAll(PLACEHOLDER_RE)) {
      const name = match[1] ?? '';
      counts[name] = (counts[name] ?? 0) + 1;
    }
  }
  return Object.fromEntries(Object.entries(counts).sort(([a], [b]) => (a < b ? -1 : 1)));
}

const dir = args(process.argv.slice(2)) ?? resolveCatalogDir();
if (!dir) {
  console.error('no catalogs found; pass --dir pointing at the catalog directory');
  process.exit(2);
}
const enBytes = readFileSync(resolve(dir, 'en.json'));
const arBytes = readFileSync(resolve(dir, 'ar.json'));
const en = JSON.parse(enBytes.toString('utf-8'));
const ar = JSON.parse(arBytes.toString('utf-8'));

const fixture = {
  sourceDir: dir,
  enSha256: sha256(enBytes),
  arSha256: sha256(arBytes),
  unitsKeys: UNITS_KEYS,
  stateKeys: STATE_KEYS,
  unitsCopy: Object.fromEntries(
    UNITS_KEYS.flatMap((key) => [
      [`en:${key}`, en[key] ?? null],
      [`ar:${key}`, ar[key] ?? null],
    ]),
  ),
  stateCopy: Object.fromEntries(
    STATE_KEYS.flatMap((key) => [
      [`en:${key}`, en[key] ?? null],
      [`ar:${key}`, ar[key] ?? null],
    ]),
  ),
  longestLabels: { en: longestValues(en, 3), ar: longestValues(ar, 3) },
  mixedScriptKeys: { en: mixedScriptValues(en), ar: mixedScriptValues(ar) },
  placeholderCounts: { en: placeholderCounts(en), ar: placeholderCounts(ar) },
  keyCounts: { en: Object.keys(en).length, ar: Object.keys(ar).length },
};

const body = `// Generated by tooling/test/corpus/i18n/generate-content-fixture.ts — do not edit.
// Source catalogs: packages/i18n/src/locales/{en,ar}.json (sha256 en ${fixture.enSha256}, ar ${fixture.arSha256})
// Regenerate with: node tooling/test/corpus/i18n/generate-content-fixture.ts --dir <catalog-dir>

export const CATALOG_SHA256: { en: string; ar: string } = ${JSON.stringify(
  { en: fixture.enSha256, ar: fixture.arSha256 },
  null,
  2,
)};

export const KEY_COUNTS = ${JSON.stringify(fixture.keyCounts)} as const;

/** Unit wording keys whose exact copy is pinned (percentage points). */
export const UNITS_KEYS: readonly string[] = ${JSON.stringify(UNITS_KEYS)};

/** State copy keys whose exact copy is pinned. */
export const STATE_KEYS: readonly string[] = ${JSON.stringify(STATE_KEYS)};

export const UNITS_COPY: Readonly<Record<string, string | null>> = ${JSON.stringify(fixture.unitsCopy, null, 2)};

export const STATE_COPY: Readonly<Record<string, string | null>> = ${JSON.stringify(fixture.stateCopy, null, 2)};

export const LONGEST_LABELS = ${JSON.stringify(fixture.longestLabels, null, 2)} as const;

export const MIXED_SCRIPT_KEYS = ${JSON.stringify(fixture.mixedScriptKeys, null, 2)} as const;

export const PLACEHOLDER_COUNTS = ${JSON.stringify(fixture.placeholderCounts, null, 2)} as const;
`;

writeFileSync(outPath, body);
console.log(`wrote ${outPath}`);
console.log(`en sha256 ${fixture.enSha256} (${fixture.keyCounts.en} keys)`);
console.log(`ar sha256 ${fixture.arSha256} (${fixture.keyCounts.ar} keys)`);
console.log(`mixed-script ar values: ${fixture.mixedScriptKeys.ar.length}`);
