#!/usr/bin/env node
/**
 * Generates tests/unit/i18n/generated/manifest-expectations.gen.ts from the
 * frozen translation-key manifest (packages/contracts/source/translation-keys.json).
 *
 * The generated module is a committed fixture: it pins the key inventory,
 * typed placeholder sets, plural groups and the manifest's SHA-256 so tests
 * detect catalog or manifest drift. Re-run this script whenever the frozen
 * manifest changes:
 *
 *   node tooling/test/corpus/i18n/generate-expectations.ts
 *
 * Translation decisions themselves stay with the locale catalog owners; this
 * tooling only derives mechanical expectations from the contract.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../../..');
const manifestPath = resolve(repoRoot, 'packages/contracts/source/translation-keys.json');
const outPath = resolve(repoRoot, 'tests/unit/i18n/generated/manifest-expectations.gen.ts');

interface KeyManifest {
  schemaVersion: string;
  keys: Record<string, readonly string[]>;
}

const manifestBytes = readFileSync(manifestPath);
const sha256 = createHash('sha256').update(manifestBytes).digest('hex');
const manifest = JSON.parse(manifestBytes.toString('utf-8')) as KeyManifest;

const keys = Object.keys(manifest.keys).sort();
const placeholders = Object.fromEntries(
  keys.map((k) => [k, [...(manifest.keys[k] ?? [])].sort()]),
) as Record<string, string[]>;
const CLDR_ARABIC_CATEGORIES = ['few', 'many', 'one', 'other', 'two', 'zero'];
const pluralGroups: Record<string, Set<string>> = {};
for (const key of keys) {
  const dot = key.lastIndexOf('.');
  if (dot === -1) continue;
  const suffix = key.slice(dot + 1);
  if (!CLDR_ARABIC_CATEGORIES.includes(suffix)) continue;
  const base = key.slice(0, dot);
  pluralGroups[base] ??= new Set();
  pluralGroups[base].add(suffix);
}
const pluralGroupsOut: Record<string, string[]> = Object.fromEntries(
  Object.entries(pluralGroups)
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([base, set]) => [base, [...set].sort()]),
);

const body = `// Generated by tooling/test/corpus/i18n/generate-expectations.ts — do not edit.
// Source: packages/contracts/source/translation-keys.json (sha256 ${sha256})
// Regenerate with: node tooling/test/corpus/i18n/generate-expectations.ts

/** Arabic requires all six CLDR plural categories; any plural group that
 * declares at least one category must declare all six. */
export const CLDR_ARABIC_CATEGORIES = ${JSON.stringify(CLDR_ARABIC_CATEGORIES)} as const;

export const MANIFEST_SHA256 = ${JSON.stringify(sha256)};

export const EXPECTED_KEYS: readonly string[] = ${JSON.stringify(keys, null, 2)};

export const EXPECTED_PLACEHOLDERS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(placeholders, null, 2)};

export const EXPECTED_PLURAL_GROUPS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(pluralGroupsOut, null, 2)};
`;

writeFileSync(outPath, body);
console.log(`wrote ${outPath} (${keys.length} keys, ${Object.keys(pluralGroupsOut).length} plural groups, manifest sha256 ${sha256})`);
