/**
 * Deck copy tables: human labels for metrics, findings, charts, quality,
 * scenario, coverage and evidence notes, in English and Arabic.
 *
 * Source: the planning locale reference (contracts/locales), which carries
 * the reviewed translations behind the in-repo translation-key manifest.
 * The canonical future home is the owned locale catalog (Cloud/i18n
 * lane); until it ships consumable values, the deck renders these
 * reference-derived strings so visible prose never falls back to raw
 * IDs or English scaffolding in Arabic decks. Every key here exists in
 * `translation-keys.json`; missing keys are a Cloud proposal, not a
 * local invention (see the private receipt).
 *
 * No placeholders are interpolated here: callers pass through only
 * exact model values alongside these labels.
 */
import type { Locale } from '@rowfolio/contracts';

const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    "metric.revenue": "Revenue",
    "metric.target_revenue": "Revenue target",
    "metric.operating_cost": "Operating cost",
    "metric.order_volume": "Order volume",
    "metric.downtime_minutes": "Downtime",
    "metric.maintenance_cost": "Maintenance cost",
    "metric.csat_score": "Satisfaction score",
    "metric.contribution": "Operating contribution",
    "metric.margin": "Contribution margin",
    "metric.marginDelta": "Margin change, percentage points",
    "metric.targetGap": "Difference from target",
    "metric.ordersChange": "Order volume change",
    "metric.downtimeChange": "Downtime change",
    "finding.north.title": "More orders. Still below target.",
    "finding.north.body": "North June revenue is {gap} below target, while order volume is {orders} higher than May.",
    "finding.downtime.title": "Downtime is moving the wrong way.",
    "finding.downtime.body": "North downtime increased {change}, from {previous} to {current} minutes.",
    "finding.quality.title": "Cleaner data. Visible limitations.",
    "finding.quality.body": "{duplicates} duplicate rows excluded, {categories} category cells normalized; {missing} optional scores remain missing.",
    "finding.quality.body.pending": "{duplicates} duplicate rows and {categories} category cells were flagged; proposed fixes apply only after approval — unapproved rows stay in the analysis. {missing} optional scores remain missing.",
    "chart.quality.summary.generic": "Issues found in the source; proposed fixes apply only after approval.",
    "finding.descriptive.title": "A descriptive view of your table",
    "finding.descriptive.body": "Business meaning has not been confirmed. These summaries describe the selected columns only.",
    "chart.north.title": "Actual revenue against target",
    "chart.downtime.title": "North downtime, May to June",
    "chart.quality.title": "Data quality, with the limits visible",
    "chart.scenario.title": "Contribution margin under the cost scenario",
    "common.actual": "Actual",
    "common.target": "Target",
    "common.baseline": "Baseline",
    "common.scenario": "Scenario",
    "quality.duplicate": "Duplicate rows",
    "quality.category": "Inconsistent category cells",
    "quality.missing": "Missing optional values",
    "quality.issues": "Quality issues",
    "quality.resolved": "Resolved",
    "quality.unresolved": "Still disclosed",
    "quality.noImputation": "Missing values are not filled in.",
    "region.North": "North",
    "region.South": "South",
    "region.East": "East",
    "region.West": "West",
    "region.Central": "Central",
    "region.Coast": "Coast",
    "period.january": "January",
    "period.february": "February",
    "period.march": "March",
    "period.april": "April",
    "period.may": "May",
    "period.june": "June",
    "period.july": "July",
    "period.august": "August",
    "period.september": "September",
    "period.october": "October",
    "period.november": "November",
    "period.december": "December",
    "common.synthetic": "Synthetic sample",
    "common.prepared": "Prepared sample",
    "common.allRegions": "All regions",
    "common.rows": "Source rows",
    "common.method": "Methodology",
    "common.source": "Source",
    "common.sheet": "Sheet",
    "common.change": "Change",
    "common.current": "Current period",
    "common.previous": "Previous period",
    "common.notAvailable": "Not available",
    "common.local": "Processed in your browser",
    "common.period": "Reporting period",
    "common.units": "Units",
    "common.verified": "Calculation verified",
    "scenario.question": "What if operating costs change?",
    "scenario.costChange": "Operating cost change",
    "scenario.assumption.revenueFixed": "Revenue stays fixed.",
    "scenario.assumption.mechanical": "Only selected operating costs change; this is not a forecast.",
    "scenario.unavailable": "Confirm compatible revenue and operating-cost columns to use this scenario.",
    "scenario.zeroRevenue": "Margin is unavailable because revenue is zero or negative.",
    "scenario.negativeCost": "This scenario requires nonnegative operating costs.",
    "export.includesScenario": "Includes the committed {change} operating-cost scenario.",
    "coverage.scheduledComplete": "Complete against the declared reporting calendar",
    "coverage.allSource": "All selected source records",
    "limitations.noCausality": "This comparison does not establish a cause.",
    "limitations.missingRetained": "Optional missing scores remain missing.",
    "limitations.contribution": "Revenue minus selected operating costs; not net profit.",
    "limitations.noForecast": "A mechanical sensitivity calculation, not a forecast.",
    "limitations.cache": "Formula caches may be stale and are not recalculated.",
    "evidence.calculation": "Calculation",
    "evidence.inputs": "Contributing values",
    "evidence.sourceRows": "Exact source rows",
    "evidence.exclusions": "Excluded records",
    "evidence.transformations": "Approved changes",
    "evidence.hash": "Source file fingerprint",
    "empty.noFindings": "No strong findings met the stated rules.",
    "empty.noData": "No usable rows were found in this table.",
    "common.rawInput": "Raw input",
    "common.retained": "Retained",
    "table.metric": "Metric",
    "table.value": "Value",
    "table.unit": "Unit",
    "quality.reconciliation": "Reconciliation",
    "scenario.layer": "Editable assumption",
    "scenario.notCommitted": "No scenario is committed for this briefing.",
  },
  ar: {
    "metric.revenue": "الإيرادات",
    "metric.target_revenue": "الإيرادات المستهدفة",
    "metric.operating_cost": "تكاليف التشغيل",
    "metric.order_volume": "حجم الطلبات",
    "metric.downtime_minutes": "وقت التوقف",
    "metric.maintenance_cost": "تكلفة الصيانة",
    "metric.csat_score": "درجة الرضا",
    "metric.contribution": "المساهمة التشغيلية",
    "metric.margin": "هامش المساهمة التشغيلية",
    "metric.marginDelta": "تغيّر الهامش بالنقاط المئوية",
    "metric.targetGap": "الفرق عن المستهدف",
    "metric.ordersChange": "التغيّر في حجم الطلبات",
    "metric.downtimeChange": "التغيّر في وقت التوقف",
    "finding.north.title": "طلبات أكثر، وإيرادات دون المستهدف.",
    "finding.north.body": "إيرادات الشمال في يونيو أقل من المستهدف بنسبة {gap}، بينما يزيد حجم الطلبات بنسبة {orders} مقارنة بمايو.",
    "finding.downtime.title": "وقت التوقف يتجه نحو الزيادة.",
    "finding.downtime.body": "زاد وقت التوقف في الشمال بنسبة {change}، من {previous} إلى {current} دقيقة.",
    "finding.quality.title": "بيانات أوضح، وحدود معلنة.",
    "finding.quality.body": "استُبعدت الصفوف المكررة وعددها {duplicates}، ووُحّدت قيم الفئات في {categories} خلايا؛ ولا تزال {missing} قيم اختيارية مفقودة.",
    "finding.quality.body.pending": "رُصدت {duplicates} صفوفاً مكررة و{categories} خلايا فئات؛ لا تُطبَّق الإصلاحات المقترحة إلا بعد الموافقة — وتبقى الصفوف غير المعتمدة ضمن التحليل. لا تزال {missing} قيم اختيارية مفقودة.",
    "chart.quality.summary.generic": "مشكلات مرصودة في المصدر؛ لا تُطبَّق الإصلاحات المقترحة إلا بعد الموافقة.",
    "finding.descriptive.title": "وصف لبيانات جدولك",
    "finding.descriptive.body": "لم تُؤكَّد الدلالة التجارية للبيانات. تصف هذه الملخصات الأعمدة المحددة فقط.",
    "chart.north.title": "الإيرادات الفعلية مقابل المستهدف",
    "chart.downtime.title": "وقت التوقف في الشمال من مايو إلى يونيو",
    "chart.quality.title": "جودة البيانات مع توضيح الحدود",
    "chart.scenario.title": "هامش المساهمة التشغيلية في سيناريو التكاليف",
    "common.actual": "الفعلي",
    "common.target": "المستهدف",
    "common.baseline": "الحالة الأساسية",
    "common.scenario": "السيناريو",
    "quality.duplicate": "صفوف مكررة",
    "quality.category": "خلايا فئات غير متسقة",
    "quality.missing": "قيم اختيارية مفقودة",
    "quality.issues": "مشكلات جودة البيانات",
    "quality.resolved": "تمت المعالجة",
    "quality.unresolved": "لا تزال معلنة",
    "quality.noImputation": "لا تُستكمَل القيم المفقودة تلقائياً.",
    "region.North": "الشمال",
    "region.South": "الجنوب",
    "region.East": "الشرق",
    "region.West": "الغرب",
    "region.Central": "الوسط",
    "region.Coast": "الساحل",
    "period.january": "يناير",
    "period.february": "فبراير",
    "period.march": "مارس",
    "period.april": "أبريل",
    "period.may": "مايو",
    "period.june": "يونيو",
    "period.july": "يوليو",
    "period.august": "أغسطس",
    "period.september": "سبتمبر",
    "period.october": "أكتوبر",
    "period.november": "نوفمبر",
    "period.december": "ديسمبر",
    "common.synthetic": "بيانات نموذجية اصطناعية",
    "common.prepared": "نموذج مُعَدّ مسبقاً",
    "common.allRegions": "جميع المناطق",
    "common.rows": "صفوف المصدر",
    "common.method": "المنهجية",
    "common.source": "المصدر",
    "common.sheet": "ورقة العمل",
    "common.change": "التغيّر",
    "common.current": "الفترة الحالية",
    "common.previous": "الفترة السابقة",
    "common.notAvailable": "غير متاح",
    "common.local": "تُعالَج داخل متصفحك",
    "common.period": "فترة التقرير",
    "common.units": "الوحدات",
    "common.verified": "تم التحقّق من الحساب",
    "scenario.question": "ماذا لو تغيّرت تكاليف التشغيل؟",
    "scenario.costChange": "التغيّر في تكاليف التشغيل",
    "scenario.assumption.revenueFixed": "تبقى الإيرادات ثابتة.",
    "scenario.assumption.mechanical": "تتغيّر تكاليف التشغيل المحددة فقط؛ وهذا ليس توقعاً.",
    "scenario.unavailable": "أكّد أعمدة الإيرادات وتكاليف التشغيل المتوافقة لاستخدام هذا السيناريو.",
    "scenario.zeroRevenue": "الهامش غير متاح لأن الإيرادات صفرية أو سالبة.",
    "scenario.negativeCost": "يتطلب هذا السيناريو تكاليف تشغيل غير سالبة.",
    "export.includesScenario": "يتضمن السيناريو المعتمد لتغيّر تكاليف التشغيل بنسبة {change}.",
    "coverage.scheduledComplete": "مكتملة وفق تقويم التقارير المعلن",
    "coverage.allSource": "جميع سجلات المصدر المحددة",
    "limitations.noCausality": "لا تثبت هذه المقارنة وجود علاقة سببية.",
    "limitations.missingRetained": "تظل الدرجات الاختيارية المفقودة دون تعويض.",
    "limitations.contribution": "الإيرادات ناقص تكاليف التشغيل المحددة؛ وليست صافي الربح.",
    "limitations.noForecast": "حساب لحساسية النتائج تجاه افتراض محدد، وليس توقعاً.",
    "limitations.cache": "قد تكون القيم المخزنة للصيغ قديمة، ولا يُعاد حسابها.",
    "evidence.calculation": "طريقة الحساب",
    "evidence.inputs": "القيم المستخدمة",
    "evidence.sourceRows": "صفوف المصدر الفعلية",
    "evidence.exclusions": "السجلات المستبعدة",
    "evidence.transformations": "التغييرات المعتمدة",
    "evidence.hash": "بصمة ملف المصدر",
    "empty.noFindings": "لم تستوفِ أي نتيجة قوية القواعد المحددة.",
    "empty.noData": "لم يُعثَر على صفوف قابلة للاستخدام في هذا الجدول.",
    "common.rawInput": "المدخلات الخام",
    "common.retained": "المحتفظ بها",
    "table.metric": "المؤشر",
    "table.value": "القيمة",
    "table.unit": "الوحدة",
    "quality.reconciliation": "المطابقة",
    "scenario.layer": "افتراض قابل للتعديل",
    "scenario.notCommitted": "لم يُعتمد أي سيناريو لهذه الإحاطة.",
  },
};

/** Localized label for a declared translation key. Throws on unknown keys: visible copy must never silently degrade to an ID. */
export function label(locale: Locale, key: string): string {
  const table = STRINGS[locale];
  const value = table[key];
  if (value === undefined) {
    throw new Error(`missing deck label for key ${JSON.stringify(key)} (${locale})`);
  }
  return value;
}

/** True when both locales carry the key. */
export function hasLabel(key: string): boolean {
  return STRINGS.en[key] !== undefined && STRINGS.ar[key] !== undefined;
}
